# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DoDetector
                                 A QGIS plugin
 Terrain change detection tool using the Digital Terrain Model of Difference (DoD) method.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-03-05
        copyright            : (C) 2026 by Laboratory for Urban Boundarie
        email                : hello@lub.global
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Laboratory for Urban Boundarie'
__date__ = '2026-03-05'
__copyright__ = '(C) 2026 by Laboratory for Urban Boundarie'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DoDetector class from file DoDetector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .dod import DoDetectorPlugin
    return DoDetectorPlugin()
